export const SITE_TPL = `
<script lang="ts">
// @@@ SOURCE CODE GENERATED by ALFRED-SERVICES
  import Cell from "@regnou.a/ui-cell"
  import Header from "@regnou.a/ui-header"
</script>
<Header/>
<Cell/>`;
